# Generated by Django 5.1.1 on 2025-03-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category_investorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraiserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('govt_id', models.CharField(max_length=50)),
                ('bank_account_details', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
