# Generated by Django 5.1.1 on 2025-03-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_ngowelfareprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngowelfareprofile',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
