# Generated by Django 5.1.1 on 2025-03-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_ngowelfareprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngowelfareprofile',
            name='category',
        ),
    ]
