# Generated by Django 5.1.1 on 2025-03-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_ngowelfareprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='preferred_categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
