# Generated by Django 5.1.1 on 2025-03-30 04:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_fundraisingproject_updated_at_transaction_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingproject',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('arts', 'Arts'), ('technology', 'Technology'), ('film', 'Film'), ('other', 'Other')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='fundraisingproject',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 3, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraisingproject',
            name='min_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='fundraisingproject',
            name='reward_tiers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fundraisingproject',
            name='social_media_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fundraisingproject',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 3, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraisingproject',
            name='story_media_link',
            field=models.URLField(default=datetime.date(2025, 3, 30)),
            preserve_default=False,
        ),
    ]
