# Generated by Django 5.1.1 on 2025-03-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraisingproject',
            name='status',
        ),
    ]
