# Generated by Django 5.1.1 on 2025-03-31 10:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_donation_ngo_ngodonationpost_donation_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngodonationpost',
            old_name='goal_amount',
            new_name='target_amount',
        ),
        migrations.AddField(
            model_name='ngodonationpost',
            name='beneficiaries',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngodonationpost',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('women_empowerment', 'Women Empowerment'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngodonationpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 31, 10, 44, 11, 736863, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngodonationpost',
            name='min_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='ngodonationpost',
            name='social_media_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ngodonationpost',
            name='supporting_documents',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngodonationpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
